#!/bin/sh
# Screenshot helper for Wayland compositors (Sway, Hyprland, etc.).
# Modified by FelipeFMA

if [ -z $WAYLAND_DISPLAY ]; then
    (>&2 echo "Wayland is not running")
    exit 1
fi

# Screenshot directory
SCREENSHOT_DIR=$(xdg-user-dir PICTURES)/Screenshots
mkdir -p "$SCREENSHOT_DIR"
SCREENSHOT_TIMESTAMP=$(date "+${WAYSHOT_DATEFMT:-%F_%H-%M-%S_%N}")
SCREENSHOT_FULLNAME="$SCREENSHOT_DIR"/screenshot_${SCREENSHOT_TIMESTAMP}.png

# Function to make a screenshot
make_screenshot() {
    case "$1" in
        -h|--help)
            echo 'Usage: screenshot [display|window|region]'
            return 0
            ;;
        region)
            grim -g "$(slurp -b '#AFAFAFAF' -c '#FF3F3FAF' -s '#00000000' -w 3 -d)" "$2"
            ;;
        window)
            # Hyprland-specific command to get the focused window's geometry
            grim -g "$(hyprctl clients -j | jq -r '.[] | select(.focused == true) | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')" "$2"
            ;;
        *)
            # Capture the entire focused output
            grim -o "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .name')" "$2"
            ;;
    esac
}

# Clipboard function
copy_to_clipboard() {
    if type wl-copy >/dev/null 2>&1; then
        wl-copy < "$1"
    else
        echo "No clipboard tool found!"
    fi
}

# Notification function
show_message() {
    if type notify-send >/dev/null 2>&1; then
        notify-send --expire-time=3000 --category=screenshot --icon="$1" "Screenshot Copied to Clipboard" "Feel free to paste it."
    fi
}

# Upload function
upload_screenshot() {
    if [ -f "$1" ]; then
        UPLOAD_LINK=$(curl -s -F "file=@$1" https://0x0.st)
        if [ ! -z "$UPLOAD_LINK" ]; then
            echo "$UPLOAD_LINK" | wl-copy
            notify-send --expire-time=3000 --category=screenshot "Upload Successful" "Link copied to clipboard!"
        else
            echo "Upload failed."
        fi
    fi
}

# Execute the main script logic
make_screenshot "$1" "$SCREENSHOT_FULLNAME"
if [ -f "$SCREENSHOT_FULLNAME" ]; then
    case "$2" in
        upload)
            upload_screenshot "$SCREENSHOT_FULLNAME"
            ;;
        *)
            copy_to_clipboard "$SCREENSHOT_FULLNAME"
            show_message "$SCREENSHOT_FULLNAME"
            ;;
    esac
fi

